---

- name: ifrename first interface

  become: True
  args:
    executable: /bin/bash

  shell:
    ip link set dev {{ ifnames.default }} down &&
    ifrename &&
    ip link set dev {{ ifnames.first }} up
